name: Docker CI Workflow

on:
  workflow_dispatch:  # Manual trigger for the workflow
    inputs:
      release_tag:
        description: 'Reminder!!! This will be deployed to Production. Please Enter Release Tag. Please make sure you have already created and pushed the entered tag, otherwise the pipeline may fail.'
        required: true
  
jobs:
  build:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment

    env:
      TAG: ${{ github.event.inputs.release_tag }}  # Set TAG environment variable from the lease_tag input

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3  # Use the latest version of the checkout action

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub securely using GitHub Secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Reference Docker Hub username stored in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Reference Docker Hub password stored in GitHub Secrets

      # Define Docker image name and tag
      - name: Set image name and tag
        id: vars
        run: |
          TIMESTAMP=$(date +'%Y%m%d%H%M')  # Current timestamp (year, month, day, hour, minute, second)
          IMAGE_NAME="${{ env.TAG }}-${TIMESTAMP}"  # Combine the lease_tag and timestamp
          
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV  # Save IMAGE_NAME for later steps
          echo "TAG=${{ env.TAG }}" >> $GITHUB_ENV  # Save TAG for later steps

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.TAG }} .

      # Tag the image for Docker Hub
      - name: Tag Docker image
        run: |
          docker tag ${{ env.IMAGE_NAME }}:${{ env.TAG }} ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
