name: Docker CI Workflow

on:
 workflow_dispatch:  # Manual trigger for the workflow

jobs:
  build:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username from GitHub secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password from GitHub secrets

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t my-app:latest .
          
      # Tag the image for Docker Hub
      - name: Tag Docker image
        run: |
          docker tag my-app:latest ${{ secrets.DOCKER_USERNAME }}/my-app:latest
          
      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest
